services:
  db:
    image: mysql:latest
    restart: always
    container_name: db
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      UPLOAD_LIMIT: 1024M

volumes:
  db_data:
