name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key 
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -p PORT root@78f9ea536125.vps.myjino.ru << 'EOF'
          cd /var/www/telegram-todo-bot || exit
          git pull
          npm install
          pm2 restart telegram-todo-bot
          EOF                                                                                          
